# Build settings

port: 4000
markdown:  kramdown
permalink: /:title/
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]
baseurl: "/Petter_Required-GitHub-activity"


# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Petter's Website"
description: "Powered by Jekyll and GitHub Pages"
author:      "Petter Wettestad"
